# Site Settings
title: myStuff
email: hans@ratzinger.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog where I will write about my experiences with my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  hansratzinger

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
